CREATE TABLE IF NOT EXISTS airport (
  id BIGSERIAL PRIMARY KEY,
  iata_code VARCHAR(3) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_airport_iata_code ON airport(LOWER(iata_code));
